### ISSUE TITLE
Homepage design - UI/UX

### ISSUE THREAD

**Issue by dtonon** [relaytools/relaycreator#1]
A first style/communication proposal for the homepage: light mode, dark mode and responsive versions.
A lot of details are missing but it can be a concrete design path to follow.

![light](https://github.com/relaytools/relaycreator/assets/89577423/4334b3da-3343-4bbc-9ddc-4fcb7b195f68)

![dark](https://github.com/relaytools/relaycreator/assets/89577423/42a03f15-4f79-4d45-808f-e544f82aa1b8)

<img width="1221" alt="Screenshot 2023-10-08 alle 21 51 43" src="https://github.com/relaytools/relaycreator/assets/89577423/7b3c5931-e877-40f9-ad20-0751e62571ed">

**Comment by jeremyd** [comment]
Lots of progress on this:

Still need:
- [ ] fix menu button when logged in dark-mode (it's invisible because it's dark)
- [ ] have menu on mobile go fullscreen?
- [ ] figure out a better navigation for relay exploring vs. "my relays"
- [ ] search field re-position/theme?

**Comment by jeremyd** [comment]
menu button - fixed
better nav for my relays - fixed
overall attempt to exact match to this design - done.
