### ISSUE TITLE
Onboarding wizard design - UI/UX

### ISSUE THREAD

**Issue by dtonon** [relaytools/relaycreator#2]
Before working on the design we need to elaborate the wizard's structure.
Let's brainstorm!

**Comment by jeremyd** [comment]
sketching out the flow as I see it here: (apologies for the colors) haha!

![wizard-diagram-1](https://github.com/relaytools/relaycreator/assets/4072/f92f9734-5f2c-4cc8-8bb3-be228f2bd6ee)

**Comment by jeremyd** [comment]
here's a deep dive of the underlying logic that controls the note flow (just for reference).

![note-flow-logic-1](https://github.com/relaytools/relaycreator/assets/4072/b9768f0f-82ca-4c71-8335-df3dcdade41e)

**Comment by jeremyd** [comment]
onboarding wizard - done
