### ISSUE TITLE
Whitelist API

### ISSUE THREAD

**Issue by supertestnet** [relaytools/relaycreator#3]
I would like to automate adding people to my whitelist via a web form. I looked at the /pages/api/ section to see if I can figure out how to do it from the existing codebase but the comments do not seem to sufficiently document how to interact with the API.

For example, the subsection relays/[id] looks promising, as it has an "allowlistpubkeys.ts" method containing code for handling a POST request, but based on the code it is not clear to me what data I am supposed to pass in via the POST request, and moreover it seems to expect I am already authenticated via a "session."

I would like to authenticate by passing an authentication token with my request, or perhaps via a challenge/response scheme that gets triggered when I send my POST request. But I think if the existing method is simply explained I can probably just find a way to automate doing whatever it currently wants. Any thoughts?

**Comment by jeremyd** [comment]
Hi there!

I recently created an example branch in the cookiecutter command line tool repository to demonstrate the use of the API to add an entry to an AllowList..  The way API authentication works is it has a challenge response using a NOSTR signature, and is given a JWT token to use.  The client can store this in their cookies for further calls.  I have an example with curl also if you're interested.

https://github.com/relaytools/cookiecutter/tree/wl

**Comment by supertestnet** [comment]
Thank you! I am definitely interested in your curl example, can you paste it?

**Comment by jeremyd** [comment]
here's an example gist.  You would need to use a command line nostr event signer, like nostril, to get the fields you would need to login.  Hope that helps!

https://gist.github.com/jeremyd/db566e609dc184d8f0bbe5654c862b6c

**Comment by jeremyd** [comment]
api documented and done.  github.com/relaytools/cookiecutter has example code and command line tool for managing lists.
